# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-Lambda
version:      0.02
version_from: lib/Sub/Lambda.pm
installdirs:  site
requires:
    Filter::Simple:                0
    Memoize:                       0
    Parse::RecDescent:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
